#!/usr/bin/env python3
"""
Generate index.yaml from the template manifests (<template>/template.yaml).

Descriptions, tags and the entrypoint live in each template's manifest; see
manifest.py for the schema. This script only combines them.
"""

import sys

import yaml

from manifest import ManifestError, load_all

# All templates are unversioned until published releases exist.
VERSION = '1.0.0'


def _env(env):
    return [{'name': v['name'], 'required': v.get('required', False), 'description': v['description']}
            for v in env]


def build_index(manifests):
    templates = []
    for name, m in manifests.items():
        if m['hidden']:
            continue
        # Keys onctl reads (name, description, config, type) keep their
        # meaning; the rest is extra and ignored by older onctl versions.
        entry = {
            'name': name,
            'version': VERSION,
            'description': m['description'],
            'config': f"{name}/{m['entrypoint']}",
            'type': m['type'],
            'tags': m['tags'],
        }
        if m.get('env'):
            entry['env'] = _env(m['env'])
        if m.get('usage'):
            entry['usage'] = [{'command': u['command'].strip(), 'description': u['description']}
                              for u in m['usage']]
        if m.get('files'):
            entry['files'] = []
            for f in m['files']:
                item = {'path': f"{name}/{f['path']}", 'type': f['type'], 'description': f['description']}
                if f.get('env'):
                    item['env'] = _env(f['env'])
                entry['files'].append(item)
        templates.append(entry)
    return {'apiVersion': 'v1', 'templates': templates}


def generate_index_yaml():
    try:
        manifests = load_all()
    except ManifestError as e:
        for line in str(e).splitlines():
            print(f"::error::{line}")
        sys.exit(1)

    index_data = build_index(manifests)
    with open('index.yaml', 'w', encoding='utf-8') as f:
        f.write("# This file is auto-generated by .github/scripts/generate_index.py\n")
        f.write("# Do not edit manually - changes will be overwritten\n")
        f.write("# To update: edit <template>/template.yaml and run the generation script\n\n")
        yaml.dump(index_data, f, default_flow_style=False, sort_keys=False,
                  allow_unicode=True, width=1000)

    print(f"Generated index.yaml with {len(index_data['templates'])} templates")
    for template in index_data['templates']:
        print(f"  - {template['name']}: {template['config']}")


if __name__ == '__main__':
    generate_index_yaml()
