- name: Install and start Docker
  hosts: onctl
  become: true  # Run tasks as sudo/root
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
